on: [push]

permissions:
  contents: read

concurrency: 
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies and build site
        run: |
          npm i
          echo -e ${{ toJSON(toJSON(github.event.commits)) }} > ./commits.json
          npx build -o ./dist --no-token-debug true
          rm -rf ./dist/node_modules
      - name: Push built to Site
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 's3.serv00.com'
          username: 'godslayerakp'
          password: '${{ secrets.SSH_PASSWORD }}'
          delete_remote_files: true
          local_path: './dist'
          remote_path: '/usr/home/godslayerakp/domains/godslayerakp.serv00.net/public_nodejs/whipeable'
      - name: Push built to Site
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 's3.serv00.com'
          username: 'godslayerakp'
          password: '${{ secrets.SSH_PASSWORD }}'
          delete_remote_files: false
          local_path: './server'
          remote_path: '/usr/home/godslayerakp/domains/godslayerakp.serv00.net/public_nodejs/whipeable'
      - name: Push built to Site
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 's3.serv00.com'
          username: 'godslayerakp'
          password: '${{ secrets.SSH_PASSWORD }}'
          delete_remote_files: false
          local_path: './server/package.json'
          remote_path: '/usr/home/godslayerakp/domains/godslayerakp.serv00.net/public_nodejs'
      - name: Dispatch Extensions
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ secrets.t }}
          event-type: update
          repository: RedMan13/my-extensions
      - name: Dispatch Discordnt
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ secrets.t }}
          event-type: update
          repository: RedMan13/discordnt
