on: [push]

permissions:
  contents: read

concurrency: 
  group: "deploy"
  cancel-in-progress: true
  #ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies and build site
        run: npm i && node ./builder
      - name: LFTP deploy action
        uses: xarses/lftp-upload-action@v0.2.0
        with:
          host: 's3.serv00.com'
          protocol: 'sftp'
          username: 'godslayerakp'
          password: '${{ secrets.SSH_PASSWORD }}'
          # for some reason serv00 isnt registered by default, so the build fails cause the key cant be verified
          ssl_verify_cert: false 
          local_path: './build'
          remote_path: '/usr/home/godslayerakp/domains/godslayerakp.serv00.net/public_html'