on: [push]

permissions:
  contents: read

concurrency: 
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies and build site
        run: |
          npm i
          echo -e ${{ toJSON(toJSON(github.event.commits)) }} > ./commits.json
          npx build -o ./dist --no-token-debug true --no-node true
          rm -rf ./dist/node_modules
      - name: ssh-scp-ssh-pipelines
        # You may pin to the exact commit or the version.
        # uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
        uses: antonov1991/ssh-scp-ssh-pipelines@v1.1.4
        with:
          # ssh remote host
          host: s3.serv00.com
          # ssh remote user
          user: godslayerakp
          # ssh remote password
          pass: '${{ secrets.SSH_PASSWORD }}'
          # execute pre-commands before scp
          first_ssh: |
            cd /usr/home/godslayerakp/domains/godslayerakp.serv00.net/public_nodejs
            rm -rf ./dist
            rm -rf ./server
            rm -f ./package-lock.json
            mkdir ./dist
            mkdir ./server
          # scp from local to remote
          scp: |
            ./dist/* => /usr/home/godslayerakp/domains/godslayerakp.serv00.net/public_nodejs/dist
            ./server/* => /usr/home/godslayerakp/domains/godslayerakp.serv00.net/public_nodejs/server
          # execute post-commands after scp
          last_ssh: |
            cd /usr/home/godslayerakp/domains/godslayerakp.serv00.net/public_nodejs
            mv ./server/package.json ./package.json
            npm i
      - name: Dispatch Extensions
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ secrets.t }}
          event-type: update
          repository: RedMan13/my-extensions
      - name: Dispatch Discordnt
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ secrets.t }}
          event-type: update
          repository: RedMan13/discordnt
